### ISSUE TITLE
Add ability to cancel current queue item

### ISSUE THREAD

**Issue by grabbou** [azproduction/promise-queue#13]
It would be cool to be able to somehow cancel a current item (e.g file download). 

We could try to use http://bluebirdjs.com/docs/api/cancellation.html or implement something that works in a similar manner but it's not tied to bluebird semantics.

I am happy to submit a pull request if that's something you would consider adding.

**Comment by azproduction** [comment]
Promises are in general are not abortable "from outside". I do not see any reason to implement it in queue.

**Comment by grabbou** [comment]
At least it would be reasonable to be able to access current item? (so it's up to user what to do in such case)
