### ISSUE TITLE
Queue Finished Event

### ISSUE THREAD

**Issue by codeandcats** [azproduction/promise-queue#14]
Would be nice if there was a simple way to subscribe to an event that fired when the queue becomes empty, without the consumer needing to look at queue lengths.

**Comment by lostinthestory** [comment]
+1
Agree that this feature would be useful.

**Comment by mbrevda** [comment]
Being that `q.add` returns a promise, you can simple collect them all and do something when their done.

```js
var tasks = []
tasks.push(q.add(/* unit of work*/))
tasks.push(q.add(/* unit of work*/))
tasks.push(q.add(/* unit of work*/))
tasks.push(q.add(/* unit of work*/))
tasks.push(q.add(/* unit of work*/))

Promise.all(tasks).then(/* do something when the queue has finished processing*/)
```

**Comment by azproduction** [comment]
Thanks @mbrevda for that code snippet. 
As it is a Promise queue then it is not a good idea to mix events into it and make chimera. 
As the problem can be addressed differently I am closing this issue.

**Comment by codeandcats** [comment]
What if the code adding items to the queue is not the code that wants to know when the queue is empty. I could build a wrapper around the queue but it would be better if it were simply baked in.

**Comment by azproduction** [comment]
@codeandcats so on every promise resolve you can check `getPendingLength()` and `getQueueLength()` if they both give 0 then there is no more promises in the pipeline.
