### ISSUE TITLE
Callback for empty queue?

### ISSUE THREAD

**Issue by pdehaan** [azproduction/promise-queue#16]
I'm currently trying to check a list of ~140 URLs to make sure I get a status code of 200/OK, and am trying to use **promise-queue**.

I'm finding that after the queue drains, the thread kind of hangs, presumably waiting for more things to get into the queue.

Is there a way to check for queue.empty and call a callback or something? or some equivalent to `Promise.all()`?
Currently I just do `if (queue.getQueueLength() === 0) process.exit(0);` which feels like a pretty huge foot gun.

**Comment by adjohnson916** [comment]
@pdehaan See my PR #9.

**Comment by megapctr** [comment]
I'm probably late to the party, but I was having the same problem. What you can do, is to create an array of all jobs you've submitted (`Queue#add` gives you a promise of that job) and feed it into `Promise.all`.

**Comment by Crowes** [comment]
Out of concern that this Mikhail has discontinued his support for this, I rewrote it into ES6 and added this event.

https://github.com/Sugarcoated/Fondant/wiki/Queue

**Comment by AndersDJohnson** [comment]
I believe this should now be resolved by the merge and publish ofhttps://github.com/azproduction/promise-queue/pull/9 according to @azproduction.

**Comment by azproduction** [comment]
Thank you, it was implemented in the latest version.
