### ISSUE TITLE
queue doesn't delay steps

### ISSUE THREAD

**Issue by brettjonesdev** [azproduction/promise-queue#3]
In your [live example](http://jsfiddle.net/RVuEU/1/), if I change the queue max size to 5 and click repeatedly, my steps execute in parallel, rather than sequentially.  Am I wrong to assume that's the point of using promise-queue is to delay subsequent steps until the previous step completes?  

Here's what I mean:
http://c.hlp.sc/3C0V220S0K11

**Comment by azproduction** [comment]
Hey, 
the first argument of the Queue is a max concurrent promises the second one is a buffer: 
```js
new Queue(1, 5);
```
So here http://jsfiddle.net/RVuEU/8/ promises are resolving one after one.

**Comment by brettjonesdev** [comment]
Ah, great didn't realize that.  Thanks!
